import {Dimensions, StyleSheet} from 'react-native';

const {width} = Dimensions.get('screen');

const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: 'white',
  },
  headerContainer: {width: '100%', alignSelf: 'center'},
  headerView: {
    paddingHorizontal: 20,
    backgroundColor: 'white',
    elevation: 4,
  },
  flatListView: {
    height: 100,
    paddingVertical: 20,
    backgroundColor: 'white',
    borderRadius: 8,
    elevation: 5,
    paddingLeft: 12,
    shadowOpacity: Platform.OS === 'ios' ? 0.2 : 0.4,
  },
  flatListItemView: {
    borderRadius: 8,
    marginHorizontal: 8,
    borderWidth: 0,
    elevation: 0,
  },
  skillViewContainer: {
    elevation: 5,
    backgroundColor: 'white',
    borderRadius: 8,
    padding: 16,
    marginVertical: 20,
    marginHorizontal: 10,
    shadowOpacity: Platform.OS === 'ios' ? 0.2 : 0.4,
  },
  ratingContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  reviewRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  recentReviewText: {lineHeight: 24, fontSize: 14},
  recentReviewView: {
    padding: 20,
    backgroundColor: 'white',
    borderRadius: 12,
    elevation: 5,
    marginBottom: 20,
    marginHorizontal: 10,
    shadowOpacity: Platform.OS === 'ios' ? 0.2 : 0.4,
  },
  reportProfileView: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    height: 72,
    elevation: 5,
    backgroundColor: 'white',
    marginBottom: 40,
    borderRadius: 12,
    marginHorizontal: 10,
    shadowOpacity: Platform.OS === 'ios' ? 0.2 : 0.4,
  },
  reportProfileText: {
    fontSize: 14,
    marginLeft: '5%',
    color: 'red',
  },
  btnView: {
    width: '100%',
    height: 80,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 10,
    backgroundColor: 'white',
    elevation: 5,
    shadowOpacity: Platform.OS === 'ios' ? 0.2 : 0.4,
    shadowColor: 'black',
  },
  buttonStyleLogin: {
    backgroundColor: 'green',
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: 'green',
  },
  requestSentButtonStyleLogin: {
    backgroundColor: 'orange',
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: 'gray',
  },
  btnTextLogin: {
    fontSize: 14,
    lineHeight: 21,
    color: 'white',
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  modalOuterView: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgb(255, 255, 255)',
  },
  modalInnerView: {
    borderRadius: 29,
    // backgroundColor: 'red',
    padding: 20,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  modalHeading: {
    fontWeight: '500',
    fontSize: 16,
    color: 'black',
    alignSelf: 'center',
    width: '100%',
    marginBottom: 40,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  modalSimpleText: {
    fontWeight: '400',
    fontStyle: 'normal',
    fontSize: 14,
    marginVertical: 16,
    textAlign: 'center',
  },
  labelContainer: {
    marginBottom: '-2%',
    width: '100%',
  },
  inputContainer: {
    borderWidth: 1,
    height: 140,
    width: '100%',
    backgroundColor: 'white',
    padding: 10,
    borderRadius: 8,
  },
  textStyle: {
    fontSize: 14,
    fontWeight: '400',
    marginLeft: 10,
    marginTop: 6,
    height: '100%',
    textAlignVertical: 'top',
  },
  modalSeparator: {
    borderWidth: 1,
    marginVertical: 16,
    width: '100%',
    borderColor: 'grey',
  },
  submitReportText: {
    fontWeight: '600',
    fontStyle: 'normal',
    fontSize: 14,
  },
  buttonsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
  },
  button: {
    width: '50%',
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  introText: {
    fontSize: 14,
    lineHeight: 21,
  },
  introView: {
    flexDirection: 'row',
    marginHorizontal: -5,
    flexWrap: 'wrap',
    paddingHorizontal: 4,
    paddingTop: 8,
  },
  introDescText: {
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 21,
  },
  skillView: {
    flexDirection: 'row',
    marginHorizontal: -5,
    flexWrap: 'wrap',
  },
  imageBoxView: {
    flexDirection: 'row',
    width: '100%',
    alignSelf: 'center',
    paddingHorizontal: 10,
    elevation: 5,
    shadowOpacity: Platform.OS === 'ios' ? 0.2 : 0.4,
  },
});

export default styles;
